---
# tasks file for ansible-role-cis-audit

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yaml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Include tasks from Ubuntu playbook"
  ansible.builtin.include_tasks: ubuntu.yaml
  when: ansible_facts['distribution'] == "Ubuntu"
